DROP TABLE IF EXISTS BAND;

CREATE TABLE BAND (
  ID   INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR2(255),
  CITY VARCHAR2(255),
  YEAR INTEGER
);

INSERT INTO BAND (ID, NAME, CITY, YEAR)
VALUES
  (1, 'Metallica', 'Los Angeles', 1981),
  (2, 'Nirvana', 'Seattle', 1987);